### ISSUE TITLE
Don't send warnings on paths with PS = 0

### ISSUE THREAD

**Issue by muell149** [cms-tsg-fog/RateMon#13]
Paths with 0 rate, due to a PS=0 should not send warning emails

**Comment by muell149** [comment]
@Andrew42, could you take a look into this if you get a chance? If you're busy I can do it too.

**Comment by avetisya** [comment]
Hi Andrew and Charlie,

Since you will need to get the prescale value anyway (which is the hard part), can you please fix it to handle the slightly more generic case of prescales which are neither 0 nor 1? You can do it like this:

if (prescale == 0) then expectedRate = 0
else expectedRate /= prescale

-- Aram
